# docker-compose.yml

version: "3.9"
services:
  app:
    platform: "linux/amd64"
    image: "ghcr.io/manuelpuchner/clubsofexcellence-htl:latest"
    volumes:
      - ./prod-ca-2021.crt:/app/prod-ca-2021.crt
      - ./prisma/prod-ca-2021.crt:/app/prisma/prod-ca-2021.crt
    build:
      context: .
      dockerfile: dockerfile
    working_dir: /app
    ports:
      - "3000:3000"
    env_file:
      - .env