apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: leoclubs-file-upload-pvc
  namespace: student-m-puchner
  labels:
    app: clubsofexcellence
spec:
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
