apiVersion: apps/v1
kind: Deployment
metadata:
  name: meow
  namespace: student-m-puchner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meow
  template:
    metadata:
      labels:
        app: meow
    spec:
      containers:
        - name: meow
          image: gcr.io/kubernetes-e2e-test-images/echoserver:2.1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: meow-svc
  namespace: student-m-puchner
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: meow
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meow-ingress
  namespace: student-m-puchner
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: student.cloud.htl-leonding.ac.at
      http:
        paths:
          - path: /m.puchner/meow(.*)$
            pathType: Prefix
            backend:
              service:
                name: meow-svc
                port:
                  number: 80
